### ISSUE TITLE
GPS_MAX_SPI_TRANSFER was not declared in this scope

### ISSUE THREAD

**Issue by SaltedBlowfish** [adafruit/Adafruit_GPS#104]
@ladyada

The variable `GPS_MAX_SPI_TRANSFER` that was added as part of this commit https://github.com/adafruit/Adafruit_GPS/commit/7bb6e004a6151b0a97cec685963b2b47b8eeb2d0#diff-ad0c0bd27aa3b33b266fdac1947162cdR212-R215 is not defined.

The missing variable is preventing successful builds. (I realize this is in the `master` branch but I noticed and thought I might save you guys some time by pointing it out now)

Thanks for all of your hard work on everything. Adafruit's products keep me loyal over and over!

**Comment by jonesbmj** [comment]
I am having the same issue, have you found a fix?

**Comment by ladyada** [comment]
hi dont use master branch, use release

**Comment by SaltedBlowfish** [comment]
> I am having the same issue, have you found a fix?

Yes. Use the katestt release instead of master. You'll see that I mentioned that the issue only affects master.
