### ISSUE TITLE
Add parse for antenna stats

### ISSUE THREAD

**Issue by clayt171** [adafruit/Adafruit_GPS#131]
Would it be possible to add antenna status parsing to the library so that the antenna being used can be called?  It would be easier to get a status if $PGTOP,11,x was parsed

**Comment by ladyada** [comment]
if you submit a PR we'd take a look for sure, we have no plans to add it

**Comment by clayt171** [comment]
Added.  Thanks much.  If I was better at writing code I could probably
write some that could do what I wanted but I'm not very good at strings.

**Comment by wijnanb** [comment]
+1
We would also like to have this feature.
