### ISSUE TITLE
Angle issue

### ISSUE THREAD

**Issue by 668catalonia** [adafruit/Adafruit_GPS#139]
Hi,
How does it measure the "angle"?
I am working with this library and the Adafruit Mini GPS, and it won't work or give me an angle that makes sense?
Thank you!

**Comment by ladyada** [comment]
angle is based on movement. an ecompass is required to get rotational directionl
https://learn.adafruit.com/search?q=gps%2520compass

**Comment by 668catalonia** [comment]
Thank you very much!
So what information does angle gives?

**Comment by ladyada** [comment]
https://www.google.com/search?client=firefox-b-1-d&q=gps+nmea+angle
