### ISSUE TITLE
The consts for update rates are misleading/missing

### ISSUE THREAD

**Issue by bogundersen** [adafruit/Adafruit_GPS#22]
Hi,

I am using the this library along with the Ultimate GPS breakout board. I would like to run it at 5Hz and I used the string in the library to do so:
# define PMTK_SET_NMEA_UPDATE_5HZ "$PMTK220,200*2C"

And while that changes the nmea output speed to 5Hz, the actual gps fix rate is still only 1Hz. So I get five equal GPS readings, then it changes, then fine equal readings...

As far as I can see, you also need to send the following string to update the fix rate to 5Hz:
$PMTK300,200,0,0,0,0*2F
If I use that, the actual GPS readings seem to change at 5Hz.

Perhaps this could be included in the library to save others some headache :)

**Comment by jaroslavas** [comment]
Can someone please give me a link to documentation of PMTK300 command? None of datasheets that are linked from [Adafruit tutorial](https://learn.adafruit.com/adafruit-ultimate-gps/downloads-and-resources) mention this command.

**Comment by Franklin97355** [comment]
There is a command sheet linked here [url] http://forum.arduino.cc/index.php?topic=258163.0 [/url]
