### ISSUE TITLE
Serial setting in leo_echo_test

### ISSUE THREAD

**Issue by corpr8** [adafruit/Adafruit_GPS#36]
Hey there,

Tried the leo_echo code on the Ultimate GPS Logger but had to change the serial.begin line as follows:

Serial.begin(9600); // this baud rate doesn't actually matter!

Leaving it as per the current commit meant that the Serial debug was garbled.

**Comment by dhiltonp** [comment]
That baud rate doesn't matter for *interfacing* with the GPS unit, but it needs to be the same baud as the terminal you are using - with arduino's terminal, it can be changed in the lower right-hand corner.

**Comment by ladyada** [comment]
dhil is right - should have closed this, for Leonardo, it does not matter as Serial is USB and baud rate is ignored
