### ISSUE TITLE
Initializing hardware serial on Mega.

### ISSUE THREAD

**Issue by ThadMartin** [adafruit/Adafruit_GPS#39]
Using Arduino 1.6.1 and an Arduino mega 2560.
In parsing.pde, line 42, I changed:
Adafruit_GPS GPS(&mySerial);
to:
Adafruit_GPS GPS(&Serial3);
After that change, it works for me.

**Comment by tapiralec** [comment]
I don't believe this is an issue. See comments in lines 31-39, as they clearly give you instructions on how to do this:
```C
// If using software serial, keep this line enabled
// (you can change the pin numbers to match your wiring):
SoftwareSerial mySerial(3, 2);

// If using hardware serial (e.g. Arduino Mega), comment out the
// above SoftwareSerial line, and enable this line instead
// (you can change the Serial number to match your wiring):

//HardwareSerial mySerial = Serial1;
```

**Comment by joesaland** [comment]
This is absolutely an issue.  Follow the instructions by commenting out the SoftwareSerial line and uncomment the HardwareSerial line and it does not work.

Simply changing 
`Adafruit_GPS GPS(&mySerial);`
to
`Adafruit_GPS GPS(&Serial1);  //or Serial2, Serial3, etc. `

And the Mega works fine with this example.  It's quite simple why it doesn't work,  trivial c++ bug from Freshman programming.  You are not passing the address to the Serial but the address to your temporary variable.

**Comment by tapiralec** [comment]
I had completely forgotten about this, but I think you're right. You should fork, edit, and make a pull request. The Adafruit people are really quick for minor changes.

**Comment by josigb** [comment]
I tested with 2 Mega 2560 and i Change to  Adafruit_GPS GPS(&Serial1); 
but in Monitor I see alway Fix: 0 and no Time and Date
When I load the Blank Sketch I see on Monitor that the GPS Module works.

When I test it with Uno on Software Serial it works.

What is wrong with the mega or the Sketch.
Is there another Line in the Sketch that was wrong?

**Comment by josigb** [comment]
I found the solution.
I Change TX and RX on MEGA and then it works.
Now is TX Mega with RX GPS connected and RX Mega with TX GPS. LOL
Is that right?

**Comment by ladyada** [comment]
new HardwareSerial examples will let you change SerialX instantiation easily - try it! :)
