### ISSUE TITLE
Save sram space and use PROGMEM

### ISSUE THREAD

**Issue by gslender** [adafruit/Adafruit_GPS#46]
As per the following, change all the CMD / PMKT strings to use PROGMEM

http://forum.arduino.cc/index.php?topic=44535.0

**Comment by ffxjslee** [comment]
https://github.com/indigoid/stabbity

I wrote a tool a while back for generating and using string table files for usage with PROGMEM.
A small thing but maybe it'll be useful :-)

**Comment by tonton81** [comment]
Serial.print(F("blah"));

**Comment by drak7** [comment]
It's been a while, but please submit a PR if you'd like to implement this!
