### ISSUE TITLE
Arduino 101 Compatibility

### ISSUE THREAD

**Issue by Arvind-TJHSST** [adafruit/Adafruit_GPS#56]
This library seems to be incompatible with the Arduino 101, with the line Adafruit_GPS GPS(&mySerial); in the example sketch giving the error "exit status 1
no matching function for call to ‘Adafruit_GPS::Adafruit_GPS(SoftwareSerial*)’"
I would appreciate some help to get this modified to work with the 101. Thanks.

**Comment by josephmeehan** [comment]
I get the same error, I have the SD card working with the Adafruit GPS logger and Arduino 101 but not the GPS, same SoftwareSerial error.  Is it possible to get a modification?  Or tips on how to make the modifications?

**Comment by josephmeehan** [comment]
Use HW Serial instead of SW serial and move the #endif in the begin function in Adafruit_GPS.cpp file above the HW serial begin call.  It works for me now.

**Comment by ladyada** [comment]
w00pz - fixed this and also added HwSerial demos for both Echo & Parsing!

**Comment by orkgks** [comment]
Arduino/Genuino MKR1000 doesn t work with adafruit gps library.Can you resolve the error or write a new library for arduino / genuino

**Comment by robotdna** [comment]
I am using HW serial instead of SW serial, my .cpp file has the HW serial call after the SW serial endif. This is not working for me- using Arduino 101.
