### ISSUE TITLE
Library support for ESP8266

### ISSUE THREAD

**Issue by da-winci** [adafruit/Adafruit_GPS#63]
The library has no support for the Wifi module ESP8266.
It seems not to work for the SoftwareSerial.
This is my code:
#include <Adafruit_GPS.h>
#include <SoftwareSerial.h>

SoftwareSerial mySerial(3, 2);
//HardwareSerial mySerial = Serial1;

Adafruit_GPS GPS(&mySerial);

void setup()  
{
  GPS.begin(9600);  
}

void loop()                     // run over and over again
{  
}

Getting following error:
error: no matching function for call to 'Adafruit_GPS::Adafruit_GPS(SoftwareSerial*)'

**Comment by capedra** [comment]
Hello, I've been facing this same issue today. NewSoftSerial doesn't work on ESP8266, Adafruit_GPS library doesn't work with anything other than AVR, so, ESP8266's SoftwareSerial is not compatible with Adafruit_GPS.

**Comment by da-winci** [comment]
I would recommend to use TinyGPS+ library instead of Adafruit_GPS_Library for the ESP8266

**Comment by architmuchhal12** [comment]
A quick question:

Will the TinyGPS library work with the Adafruit GPS Sensor?

**Comment by drak7** [comment]
ESP8266 support fixed in commit [e214a45](https://github.com/adafruit/Adafruit_GPS/commit/e214a45ed6bd974adf71f3fb91586facb327eaf8)
