### ISSUE TITLE
Arduino/Genuino MKR1000 doesn t work with adafruit gps library

### ISSUE THREAD

**Issue by orkgks** [adafruit/Adafruit_GPS#65]
Arduino/Genuino MKR1000 doesn t work with adafruit gps library.Can you resolve the error or write a new library for arduino / genuino

arduino version. 1.6.13
board arduino/genuino MKR1000

**Comment by ladyada** [comment]
use hardware serial, its been tested on the samd21 :)

**Comment by orkgks** [comment]
I understand.How to make good connections. Will only connect to tx and rx and 5v , gnd
