### ISSUE TITLE
Arduino 101 Incompatible 

### ISSUE THREAD

**Issue by robotdna** [adafruit/Adafruit_GPS#78]
Hi,

I am using an Intel Curie Arduino 101 board with IDE version 1.8.8. I successfully complied and uploaded the "echo" example sketch to an Arduino UNO, but when changing to hardware serial to use my Arduino 101 board (yes, I swapped COM ports and board type) and commenting out the software serial lines as directed in the script I obtain these error messages:

`echo:98:8: error: expected constructor, destructor, or type conversion before ‘(’ token
 SIGNAL(TIMER0_COMPA_vect) {
        ^
echo:98:7: error: expected constructor, destructor, or type conversion before ‘(’ token
 SIGNAL(TIMER0_COMPA_vect) {
       ^
/tmp/arduino_modified_sketch_393384/echo.ino: In function ‘void useInterrupt(boolean)’:
echo:111:5: error: ‘OCR0A’ was not declared in this scope
     OCR0A = 0xAF;
     ^
echo:112:5: error: ‘TIMSK0’ was not declared in this scope
     TIMSK0 |= _BV(OCIE0A);
     ^
In file included from /home/user/.arduino15/packages/Intel/hardware/arc32/2.0.4/system/libarc32_arduino101/common/board.h:42:0,
                 from /home/user/.arduino15/packages/Intel/hardware/arc32/2.0.4/cores/arduino/UARTClass.h:25,
                 from /home/user/.arduino15/packages/Intel/hardware/arc32/2.0.4/variants/arduino_101/variant.h:39,
                 from /home/user/.arduino15/packages/Intel/hardware/arc32/2.0.4/cores/arduino/Arduino.h:118,
                 from sketch/echo.ino.cpp:1:
echo:112:19: error: ‘OCIE0A’ was not declared in this scope
     TIMSK0 |= _BV(OCIE0A);
                   ^
/home/user/.arduino15/packages/Intel/hardware/arc32/2.0.4/system/libarc32_arduino101/common/misc/util.h:103:26: note: in definition of macro ‘_BV’
 #define _BV(bit) (1U << (bit))
                          ^
echo:116:5: error: ‘TIMSK0’ was not declared in this scope
     TIMSK0 &= ~_BV(OCIE0A);
     ^
In file included from /home/user/.arduino15/packages/Intel/hardware/arc32/2.0.4/system/libarc32_arduino101/common/board.h:42:0,
                 from /home/user/.arduino15/packages/Intel/hardware/arc32/2.0.4/cores/arduino/UARTClass.h:25,
                 from /home/user/.arduino15/packages/Intel/hardware/arc32/2.0.4/variants/arduino_101/variant.h:39,
                 from /home/user/.arduino15/packages/Intel/hardware/arc32/2.0.4/cores/arduino/Arduino.h:118,
                 from sketch/echo.ino.cpp:1:
echo:116:20: error: ‘OCIE0A’ was not declared in this scope
     TIMSK0 &= ~_BV(OCIE0A);
                    ^
/home/user/.arduino15/packages/Intel/hardware/arc32/2.0.4/system/libarc32_arduino101/common/misc/util.h:103:26: note: in definition of macro ‘_BV’
 #define _BV(bit) (1U << (bit))
                          ^
exit status 1
expected constructor, destructor, or type conversion before ‘(’ token`

Any idea why this is not functioning? I can communicate with this board with other scripts, but the GPS ones (specifically echo and parsing) have compiling errors.

**Comment by drak7** [comment]
We've reworked the examples into SoftwareSerial and HardwareSerial, please try with the HardwareSerial examples and open a new issue if you still run into problems.
