### ISSUE TITLE
Possible integration with the arduino mkr boards (SAMD21 architecture)??

### ISSUE THREAD

**Issue by TwinedGemini** [adafruit/Adafruit_GPS#79]
Hi is it possible to modify the library to work with the SAMD21 architecture for the MKR boards??

I know that libraries such as SoftSerial, NeoSerial and AltSerial doesn't work with the SAMD21, this is not the issue as I can gain more HWSerials. However, it doesn't seem like I can generate any data output from the Ultimate GPS other than restart codes...

I've check the GPS and code on the UNO and everything works fine. It would really be helpful for alot of people (I think), as these boards have the size and functionality suited for small IoT projects.

thanks in advance

**Comment by ladyada** [comment]
this library has been tested a lot with samd21, it works great with Serial1 (the hardware serial port). we hvae tested GPS FeatherWing + all Adafruit Feather SAMD21's and work great
