### ISSUE TITLE
Inefficiencies in checksum code in parse()!

### ISSUE THREAD

**Issue by srob1** [adafruit/Adafruit_GPS#84]
Processing NMEA sentences is somewhat time critical in order to keep up with them.

The checksum code at the start of parse() is extremely inefficient, as it invokes strlen() three times and then again in the condition portion of the checksum for-loop, which causes strlen to be invoked _EVERY_ time through the loop (i.e., once for every character in the NMEA sentence)! 

The parse() routine should compute strlen(nmea) _ONCE_ at the top of the routine, and store the result in a local variable that is used throughout the routine, as the length is invariant inside parse().

Cleaning this up should save a ton of time.

**Comment by ladyada** [comment]
please submit a PR and we'll test it out :) compared to the time it takes to receive a single character over UART, the strlens() are essentially instant
